const state={plan:null,plans:[]};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const key=prefix=>`${prefix}-${Date.now()}-${crypto.randomUUID()}`;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=error?'show error':'show';setTimeout(()=>el.className='',3200)}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({detail:'响应无法解析'}));if(!response.ok)throw new Error(data.fields?.map(x=>`${x.field}: ${x.message}`).join('；')||data.detail||'请求失败');return data}
function formObject(form){return Object.fromEntries(new FormData(form).entries())}
async function loadPlans(){try{const data=await api('/api/plans');state.plans=data.plans||[];renderPlanList()}catch(e){toast(e.message,true)}}
function renderPlanList(){const host=$('#plan-list');host.innerHTML=state.plans.map(p=>`<button class="plan-link ${state.plan?.id===p.id?'active':''}" data-plan="${esc(p.id)}"><b>${esc(p.venueName)}</b><span>${esc(p.performanceDate)} · v${p.version} · ${esc(p.status)}</span></button>`).join('')||'<p class="muted">暂无方案</p>';host.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>openPlan(b.dataset.plan))}
async function openPlan(id){try{state.plan=await api(`/api/plans/${encodeURIComponent(id)}`);render();await Promise.all([loadAudit(),loadPlans()])}catch(e){toast(e.message,true)}}
async function refreshAfter(message){render();await Promise.all([loadAudit(),loadPlans()]);toast(message)}

function render(){const p=state.plan;$('#empty-state').hidden=!!p;$('#plan-view').hidden=!p;if(!p)return;$('#plan-title').textContent=p.venueName;$('#plan-meta').textContent=`演出 ${p.performanceDate} · 负责人 ${p.ownerName} · 总额定 ${p.ratedTotalLoadKg} kg`;$('#plan-version').textContent=p.version;$('#plan-status').textContent=p.status;$('#open-count').textContent=p.issues.filter(i=>i.status!=='closed').length;renderPoints();renderTests();renderIssues();renderTasks();renderCredentials();const frozen=p.status==='approved';$$('#plan-edit-form input,#plan-edit-form button,#point-form input,#point-form select,#point-form button,#test-form input,#test-form select,#test-form button,#batch-test-form input,#batch-test-form select,#batch-test-form button,#review-form input,#review-form select,#review-form button').forEach(x=>x.disabled=frozen);$('#edit-plan').disabled=frozen;$('#open-batch').disabled=frozen;$('#credential-form button').disabled=!frozen}
function options(selected=''){return state.plan.points.map(p=>`<option value="${esc(p.id)}" ${p.id===selected?'selected':''}>${esc(p.label)} · ${esc(p.id)}</option>`).join('')}
function renderPoints(){const p=state.plan;$('#point-form select[name=redundantPointId]').innerHTML='<option value="">暂未指定</option>'+options();$('#test-form select[name=pointId]').innerHTML=options();$('#point-list').innerHTML=p.points.map(x=>`<div class="data-row"><div><b>${esc(x.label)}</b><small>${esc(x.id)} · 配置 r${x.configRevision}</small></div><div><span>${x.plannedLoadKg} / ${x.ratedLoadKg} kg</span><small>计划 / 额定</small></div><div><span>${esc(x.deviceModel)}</span><small>${esc(x.cableSpec)} · 证书 ${esc(x.certificateExpiresOn)}</small></div><div class="row-actions"><button class="ghost edit-point" data-id="${esc(x.id)}">编辑</button><button class="ghost remove-point" data-id="${esc(x.id)}">移除</button></div></div>`).join('')||'<p class="muted">尚未登记吊点</p>';$$('.edit-point').forEach(b=>b.onclick=()=>editPoint(b.dataset.id));$$('.remove-point').forEach(b=>b.onclick=()=>removePoint(b.dataset.id));renderBatchRows()}
function editPoint(id){const point=state.plan.points.find(x=>x.id===id),form=$('#point-form');if(!point)return;form.dataset.editId=id;for(const name of ['label','ratedLoadKg','plannedLoadKg','deviceModel','cableSpec','primaryPointId','redundantPointId','certificateExpiresOn'])form.elements[name].value=point[name]??'';$('#point-submit-label').textContent='保存吊点修订';form.hidden=false;form.scrollIntoView({behavior:'smooth',block:'center'})}
async function removePoint(id){const point=state.plan.points.find(x=>x.id===id);try{const check=await api(`/api/plans/${state.plan.id}/points/${id}/removal-check`);if(!check.allowed){toast(`无法移除：${check.message}`,true);return}if(!confirm(`服务端检查结论：${check.message}\n确认移除吊点 ${point?.label||id}？`))return;state.plan=await api(`/api/plans/${state.plan.id}/points/${id}`,{method:'DELETE',body:JSON.stringify({expectedVersion:state.plan.version,idempotencyKey:key('point-remove')})});await refreshAfter('吊点已受控移除，审计事实已保存')}catch(e){toast(`无法移除：${e.message}`,true)}}
function renderTests(){const tests=[...state.plan.tests].reverse();$('#test-list').innerHTML=tests.map(t=>{const point=state.plan.points.find(p=>p.id===t.pointId);return `<div class="data-row"><div><b>${esc(point?.label||t.pointId)}</b><small>${t.testKind==='retest'?'整改复测':'初次试验'} · ${esc(t.performedBy)}</small></div><div><span>${t.measuredLoadKg} / ${t.targetLoadKg} kg</span><small>实测 / 目标</small></div><div><span>${t.holdSeconds} 秒 · ${t.deformationMm} mm</span><small>${esc(t.evidenceDigest)}</small></div><div><span class="badge ${t.currentConfiguration&&t.outcome==='pass'?'':'warn'}">${t.currentConfiguration?(t.outcome==='pass'?'当前配置·通过':'当前配置·失败'):'旧配置历史'}</span></div></div>`}).join('')||'<p class="muted">尚无试验记录</p>'}
function renderIssues(){const issues=[...state.plan.issues].sort((a,b)=>(a.status==='closed')-(b.status==='closed'));$('#issue-list').innerHTML=issues.map(i=>{const point=state.plan.points.find(p=>p.id===i.pointId);return `<div class="data-row issue-${i.status==='closed'?'closed':'open'}"><div><b>${esc(i.ruleCode)}</b><small>${esc(point?.label||'方案级')} · ${esc(i.id)}</small></div><div><span>${esc(i.description)}</span><small>${esc(i.remediationNote||'尚无整改说明')}</small></div><div><span class="badge ${i.status==='closed'?'':'warn'}">${esc(i.status)}</span></div><div>${i.status!=='closed'?`<button class="ghost remediate" data-issue="${esc(i.id)}">${i.status==='open'?'提交整改':'再次整改'}</button>`:'已关闭'}</div></div>`}).join('')||'<div class="verify">规则检查未发现阻断风险</div>';$$('.remediate').forEach(b=>b.onclick=()=>remediate(b.dataset.issue))}
function renderTasks(){const tasks=[...(state.plan.retestTasks||[])].sort((a,b)=>(a.status!=='pending')-(b.status!=='pending'));$('#task-list').innerHTML=tasks.map(t=>{const point=state.plan.points.find(p=>p.id===t.pointId);const reasons=t.unmetConditions?.join('；')||t.closureBasis||'等待满足最低载荷、60 秒保持、2 mm 变形与通过结论';return `<div class="data-row"><div><b>${esc(point?.label||t.pointId)}</b><small>${esc(t.id)} · ${esc(t.status)}</small></div><div><span>${t.conditions.minimumTargetLoadKg} kg / ${t.conditions.minimumHoldSeconds} 秒</span><small>变形 ≤ ${t.conditions.maximumDeformationMm} mm</small></div><div><span>${esc(reasons)}</span><small>尝试 ${t.attemptTestIds?.length||0} 次</small></div><div><span class="badge ${t.status==='closed'?'':'warn'}">${esc(t.status)}</span></div></div>`}).join('')||'<p class="muted">尚无复测任务</p>';const select=$('#test-form select[name=retestTaskId]');select.innerHTML='<option value="">初试无需选择</option>'+tasks.filter(t=>t.status==='pending').map(t=>`<option value="${esc(t.id)}">${esc(state.plan.points.find(p=>p.id===t.pointId)?.label||t.pointId)} · ${esc(t.id)}</option>`).join('')}
async function remediate(issueId){const issue=state.plan.issues.find(i=>i.id===issueId);const note=prompt('整改说明');if(!note)return;const body={idempotencyKey:key('remediate'),expectedVersion:state.plan.version,issueId,note,revisedBy:state.plan.ownerName};if(issue.ruleCode==='REDUNDANCY_MISSING'){const id=prompt('请输入有效冗余吊点 ID');if(!id)return;body.redundantPointId=id}else if(issue.ruleCode==='POINT_OVERLOAD'||issue.ruleCode==='PLAN_OVERLOAD'){const point=issue.pointId||prompt('请输入需要降低载荷的吊点 ID');if(!point)return;body.pointId=point;const load=prompt('请输入修订后的计划载荷 kg');if(!load)return;body.plannedLoadKg=Number(load)}else if(issue.ruleCode==='CERTIFICATE_EXPIRED'){const date=prompt('请输入新证书到期日 YYYY-MM-DD');if(!date)return;body.certificateExpiresOn=date}try{state.plan=await api(`/api/plans/${state.plan.id}/remediations`,{method:'POST',body:JSON.stringify(body)});await refreshAfter('整改修订和绑定复测任务已保存')}catch(e){toast(e.message,true)}}
function renderCredentials(){const p=state.plan;$('#credential-list').innerHTML=p.credentials.map(c=>`<div class="data-row"><div><b>${esc(c.id)}</b><small>序号 ${c.sequence}</small></div><div><span>${esc(c.issuedBy)}</span><small>${new Date(c.issuedAt).toLocaleString()}</small></div><div><span title="${esc(c.frozenDigest)}">冻结摘要 ${esc(c.frozenDigest.slice(0,16))}…</span><small>凭据摘要 ${esc(c.credentialDigest.slice(0,16))}…</small></div><div><button class="ghost verify-credential" data-id="${esc(c.id)}">方案内核验</button></div></div>`).join('')||'<p class="muted">尚未签发凭据</p>';$$('.verify-credential').forEach(b=>b.onclick=()=>verifyCredential(b.dataset.id))}
async function verifyCredential(id){try{const data=await api(`/api/plans/${state.plan.id}/credentials/${id}/verify`);toast(data.verification.message,!data.verification.valid)}catch(e){toast(e.message,true)}}
async function loadAudit(){if(!state.plan)return;try{const data=await api(`/api/plans/${state.plan.id}/audit`);const v=data.verification;$('#audit-verification').innerHTML=`<div class="verify ${v.valid?'':'bad'}">${esc(v.message)}</div>`;$('#audit-list').innerHTML=data.records.map(r=>`<div class="timeline-item"><b>#${r.sequence} ${esc(r.action)}</b><div>${esc(r.actor)} · ${new Date(r.at).toLocaleString()}</div><small class="muted">摘要 ${esc(r.digest.slice(0,20))}…</small></div>`).join('')||'<p class="muted">暂无审计记录</p>'}catch(e){toast(e.message,true)}}
function renderBatchRows(){const host=$('#batch-rows');host.innerHTML=state.plan.points.map((p,index)=>`<fieldset class="batch-row" data-point="${esc(p.id)}" data-digest="${esc(p.configDigest)}"><legend>${index+1}. ${esc(p.label)} · r${p.configRevision}</legend><label>目标 kg<input name="target" type="number" min="0.01" step="0.01" value="${p.plannedLoadKg}" required></label><label>实测 kg<input name="measured" type="number" min="0.01" step="0.01" value="${p.plannedLoadKg}" required></label><label>保持秒<input name="hold" type="number" min="1" value="60" required></label><label>变形 mm<input name="deformation" type="number" min="0" step="0.01" value="0.5" required></label><label>结论<select name="outcome"><option value="pass">通过</option><option value="fail">失败</option></select></label><label>证据摘要<input name="evidence" required></label><label>试验员<input name="tester" required></label></fieldset>`).join('')||'<p class="muted">请先登记吊点</p>'}

$('#global-verify-form').onsubmit=async e=>{e.preventDefault();const b=formObject(e.target),host=$('#global-verify-result');try{const data=await api(`/api/credentials/${encodeURIComponent(b.credentialId)}/verify?digest=${encodeURIComponent(b.digest)}`),v=data.verification;host.hidden=false;host.innerHTML=`<div class="verify ${v.valid?'':'bad'}"><b>${v.valid?'核验有效':'核验无效'}</b> · ${esc(v.message)}<br><small>${esc(v.venueName)} · ${esc(v.performanceDate)} · 序号 ${v.sequence} · ${esc(v.issuedBy)} · ${new Date(v.issuedAt).toLocaleString()}</small><div>凭据摘要 ${v.checks.credentialDigest?'一致':'失败'} · 冻结清单 ${v.checks.frozenManifest?'一致':'失败'} · 冻结引用 ${v.checks.frozenReference?'一致':'失败'} · 序号 ${v.checks.sequence?'有效':'失败'} · 审计链 ${v.checks.auditChain?'有效':'失败'}</div></div>`}catch(err){host.hidden=true;toast(err.message,true)}};
$('#new-plan').onclick=()=>$('#create-dialog').showModal();$('#close-dialog').onclick=()=>$('#create-dialog').close();
$$('.toggle').forEach(b=>b.onclick=()=>{$(`#${b.dataset.target}`).hidden=false});$$('.cancel').forEach(b=>b.onclick=()=>{$(`#${b.dataset.target}`).hidden=true});
$('#edit-plan').onclick=()=>{const p=state.plan,f=$('#plan-edit-form');for(const name of ['venueName','performanceDate','ratedTotalLoadKg','ownerName'])f.elements[name].value=p[name];f.hidden=false};
$('#open-batch').onclick=()=>{$('#batch-test-form').hidden=false;renderBatchRows()};
$('#create-form').onsubmit=async e=>{e.preventDefault();const b=formObject(e.target);b.ratedTotalLoadKg=Number(b.ratedTotalLoadKg);b.idempotencyKey=key('create');try{state.plan=await api('/api/plans',{method:'POST',body:JSON.stringify(b)});$('#create-dialog').close();e.target.reset();await refreshAfter('吊挂方案已创建')}catch(err){toast(err.message,true)}};
$('#plan-edit-form').onsubmit=async e=>{e.preventDefault();const b=formObject(e.target);b.ratedTotalLoadKg=Number(b.ratedTotalLoadKg);b.expectedVersion=state.plan.version;b.idempotencyKey=key('plan-update');try{state.plan=await api(`/api/plans/${state.plan.id}`,{method:'PATCH',body:JSON.stringify(b)});e.target.hidden=true;await refreshAfter('方案基础信息已修订并重算风险')}catch(err){toast(err.message,true)}};
$('#point-form').onsubmit=async e=>{e.preventDefault();const b=formObject(e.target);b.ratedLoadKg=Number(b.ratedLoadKg);b.plannedLoadKg=Number(b.plannedLoadKg);b.expectedVersion=state.plan.version;b.idempotencyKey=key(e.target.dataset.editId?'point-update':'point-add');const id=e.target.dataset.editId,path=id?`/api/plans/${state.plan.id}/points/${id}`:`/api/plans/${state.plan.id}/points`;try{state.plan=await api(path,{method:id?'PATCH':'POST',body:JSON.stringify(b)});e.target.reset();delete e.target.dataset.editId;e.target.hidden=true;$('#point-submit-label').textContent='保存吊点';await refreshAfter(id?'吊点配置已修订，旧配置试验保留为历史':'吊点已登记')}catch(err){toast(err.message,true)}};
$('#test-form select[name=testKind]').onchange=e=>{const retest=e.target.value==='retest';e.target.form.elements.retestTaskId.required=retest;if(!retest)e.target.form.elements.retestTaskId.value=''};
$('#test-form select[name=retestTaskId]').onchange=e=>{const task=state.plan.retestTasks.find(t=>t.id===e.target.value);if(!task)return;const f=e.target.form;f.elements.pointId.value=task.pointId;f.elements.targetLoadKg.value=task.conditions.minimumTargetLoadKg;f.elements.holdSeconds.value=task.conditions.minimumHoldSeconds;f.elements.deformationMm.value=task.conditions.maximumDeformationMm};
$('#test-form').onsubmit=async e=>{e.preventDefault();const b=formObject(e.target);['targetLoadKg','measuredLoadKg','deformationMm'].forEach(k=>b[k]=Number(b[k]));b.holdSeconds=Number(b.holdSeconds);b.expectedVersion=state.plan.version;b.idempotencyKey=key('test');const point=state.plan.points.find(p=>p.id===b.pointId);b.pointConfigDigest=point?.configDigest||'';if(b.testKind!=='retest')delete b.retestTaskId;try{state.plan=await api(`/api/plans/${state.plan.id}/tests`,{method:'POST',body:JSON.stringify(b)});e.target.hidden=true;await refreshAfter('载荷试验事实已归档')}catch(err){toast(err.message,true)}};
$('#batch-test-form').onsubmit=async e=>{e.preventDefault();const tests=$$('.batch-row').map(row=>({pointId:row.dataset.point,pointConfigDigest:row.dataset.digest,testKind:'initial',targetLoadKg:Number(row.elements.target.value),measuredLoadKg:Number(row.elements.measured.value),holdSeconds:Number(row.elements.hold.value),deformationMm:Number(row.elements.deformation.value),outcome:row.elements.outcome.value,evidenceDigest:row.elements.evidence.value,performedBy:row.elements.tester.value}));try{const data=await api(`/api/plans/${state.plan.id}/tests/batch`,{method:'POST',body:JSON.stringify({idempotencyKey:key('test-batch'),expectedVersion:state.plan.version,tests})});state.plan=data.plan;e.target.hidden=true;await refreshAfter(`批次 ${data.batchId} 已原子归档 ${data.tests.length} 条试验`)}catch(err){toast(err.message,true)}};
$('#review-form').onsubmit=async e=>{e.preventDefault();const b=formObject(e.target);b.expectedVersion=state.plan.version;b.idempotencyKey=key('review');try{state.plan=await api(`/api/plans/${state.plan.id}/review`,{method:'POST',body:JSON.stringify(b)});await refreshAfter(b.decision==='approve'?'方案已批准冻结':'方案已退回')}catch(err){toast(err.message,true)}};
$('#credential-form').onsubmit=async e=>{e.preventDefault();const b=formObject(e.target);b.expectedVersion=state.plan.version;b.idempotencyKey=key('credential');try{state.plan=await api(`/api/plans/${state.plan.id}/credentials`,{method:'POST',body:JSON.stringify(b)});await refreshAfter('放行凭据已签发并封存')}catch(err){toast(err.message,true)}};
$('#refresh-audit').onclick=loadAudit;loadPlans();
